name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
    build:
      strategy:
        matrix:
            os: [ubuntu-24.04, windows-2022, macos-14]
      runs-on: ${{ matrix.os }}
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Code
        run: cargo build -vv --workspace --locked
      - name: Test Code
        run: cargo test -vv --workspace --no-fail-fast --locked