name: Check Code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Code Style
        run: cargo fmt -v --all --check
      - name: Check Code
        run: cargo check -vv --workspace --keep-going --locked
      - name: Check Code with Clippy
        run: cargo clippy -vv --workspace --keep-going --locked